dev: cuda
out_dir: outputs/example_sequence_outputs
out_name: sample_run
input_list: inputs/example_list_sample_seqs.txt
input_dir: inputs/example_pdbs
chain_dict_json: null
model:
  check_path: vanilla_model_weights/pottsmpnn_20.pt
  hidden_dim: 128
  edge_features: 128
  potts_dim: 400
  num_layers: 3
  num_edges: 48
  vocab: 21
inference:
  num_samples: 1
  temperature: 0.1
  noise: 0.0
  skip_gaps: false
  fix_decoding_order: true
  decoding_order_offset: 0
  optimization_mode: potts
  optimization_temperature: 0.0
  binding_energy_optimization: none
  binding_energy_json: null
  binding_energy_cutoff: 8
  optimize_pdb: false
  optimize_fasta: ''
  write_pdb: true
  fixed_positions_json: ''
  pssm_json: ''
  omit_AA_json: ''
  bias_AA_json: ''
  tied_positions_json: ''
  bias_by_res_json: ''
  omit_AAs: []
  pssm_threshold: 0.0
  pssm_multi: 0.0
  pssm_log_odds_flag: false
  pssm_bias_flag: false
